WITH RANKED AS (
    SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN
    FROM ECOLI_DATA
),
TOTAL_CNT AS (
    SELECT COUNT(*) AS TOTAL
    FROM ECOLI_DATA
)
SELECT R.ID,
       CASE WHEN R.RN <= T.TOTAL * 0.25 THEN 'CRITICAL'
            WHEN R.RN <= T.TOTAL * 0.5 THEN 'HIGH'
            WHEN R.RN <= T.TOTAL * 0.75 THEN 'MEDIUM'
            ELSE 'LOW' END AS COLONY_NAME
FROM RANKED R JOIN TOTAL_CNT T
ORDER BY r.ID