SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM (
    SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME, AO.SEX_UPON_OUTCOME
    FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID 
    WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
    )A
WHERE A.SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY 1

