WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, 0 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, GENERATION + 1
    FROM ECOLI_DATA E INNER JOIN ECOLI_TREE ET ON E.PARENT_ID = ET.ID
),
NO_CHILD_ECOLI AS (
    SELECT E.ID, GENERATION
    FROM ECOLI_TREE ET LEFT JOIN ECOLI_DATA E ON ET.ID = E.PARENT_ID
    WHERE E.ID IS NULL
)

SELECT COUNT(*) AS COUNT, GENERATION + 1 AS GENERATION
FROM NO_CHILD_ECOLI
GROUP BY 2
ORDER BY 2
