SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
                   JOIN PATIENT P ON P.PT_NO = A.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY 6