WITH SKILLS AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE EXISTS(
    SELECT 1
    FROM SKILLS
    WHERE DEVELOPERS.SKILL_CODE & SKILLS.CODE > 0
)
ORDER BY 1