WITH MAX_SIZE_BY_YEAR AS (
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
)

SELECT 
    EXTRACT(YEAR FROM E.DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN MAX_SIZE_BY_YEAR M
    ON EXTRACT(YEAR FROM E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV