SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO I JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_FISH ON I.FISH_TYPE = MAX_FISH.FISH_TYPE AND I.LENGTH = MAX_FISH.MAX_LENGTH
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY 1