SELECT CITY, LENGTH(CITY)
FROM (SELECT CITY, LENGTH(CITY)
      FROM STATION
      WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
      ORDER BY CITY
      LIMIT 1
) AS SHORT_CITY

UNION ALL

SELECT CITY, LENGTH(CITY)
FROM (SELECT CITY, LENGTH(CITY)
      FROM STATION
      WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
      ORDER BY CITY
      LIMIT 1
) AS LONG_CITY