SELECT CASE WHEN MAX(CASE WHEN NAME = 'Python' THEN 1 ELSE 0 END) = 1
            AND MAX(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) = 1 THEN 'A'
            WHEN MAX(CASE WHEN NAME = 'C#' THEN 1 ELSE 0 END) = 1 THEN 'B'
            WHEN MAX(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) = 1 THEN 'C'
            ELSE NULL END AS GRADE, 
            ID, EMAIL
FROM DEVELOPERS D JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) = S.CODE
GROUP BY 2, 3
HAVING GRADE IS NOT NULL
ORDER BY 1, 2
